apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    name: mysql-pv
spec:
  capacity:
    storage: 20Gi
  storageClassName: manual    
  accessModes:
    - ReadWriteOnce
      #  claimRef:
      #name: mysql-pvc
      #namespace: main
      #persistentVolumeReclaimPolicy: Recycle
      #gcePersistentDisk:
      #pdName: mysql-disk
      # fsType: ext4
  hostPath:
    path: "/mysql-disk"
